### ISSUE TITLE
Highlight Mentions

### ISSUE THREAD

**Issue by Firebottle** [ebiggz/MixrElixr#21]
Highlight messages that mention the logged in user with a different background color.

**Comment by Firebottle** [comment]
Highlights both direct @ mentions as well as just the name spelled out.

![image](https://user-images.githubusercontent.com/17416635/32136360-00bf210c-bbd2-11e7-8795-3a0e92fd10cc.png)

**Comment by ebiggz** [comment]
This is awesome. I updated it to use a RegEx instead of raw string comparisons. I know you hate them, but this is a perfect use case for regexes. Now T could use this feature without issue because the regex requires that there is a "word boundary" on either side of the username. So the message will only get highlighted if there is a T by itself. But not when its with in a word.  This combined with #8 I think it will cover most, if not all, use cases.
